ALTER TABLE Clans
DROP CONSTRAINT fk_owner_id;

DROP TABLE IF EXISTS Records;
DROP TABLE IF EXISTS Exercises;
DROP TABLE IF EXISTS Workouts;
DROP TABLE IF EXISTS Subscriptions;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Gyms;
DROP TABLE IF EXISTS Clans;
