INSERT INTO exercises (name) VALUES
                                 ('Squats'),
                                 ('Push-ups'),
                                 ('Pull-ups'),
                                 ('Deadlifts'),
                                 ('Bench press'),
                                 ('Overhead press'),
                                 ('Bent-over row'),
                                 ('Military press'),
                                 ('French press'),
                                 ('Dumbbell flyes'),
                                 ('Dumbbell bicep curls'),
                                 ('Dumbbell tricep extensions'),
                                 ('Cable flyes'),
                                 ('Cable crossovers'),
                                 ('Abdominal crunches'),
                                 ('Plank'),
                                 ('Leg raises'),
                                 ('Hyperextension'),
                                 ('Lat pulldown'),
                                 ('Cable row'),
                                 ('Leg press'),
                                 ('Leg curls'),
                                 ('Leg extensions'),
                                 ('Standing calf raises'),
                                 ('Seated calf raises');