// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	storage "GYMBRO/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *UserRepository) GetUserByEmail(email string) (storage.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 storage.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (storage.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) storage.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(storage.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: id
func (_m *UserRepository) GetUserByID(id int) (storage.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 storage.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (storage.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) storage.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(storage.User)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterNewUser provides a mock function with given fields: usr
func (_m *UserRepository) RegisterNewUser(usr storage.User) (int, error) {
	ret := _m.Called(usr)

	if len(ret) == 0 {
		panic("no return value specified for RegisterNewUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.User) (int, error)); ok {
		return rf(usr)
	}
	if rf, ok := ret.Get(0).(func(storage.User) int); ok {
		r0 = rf(usr)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(storage.User) error); ok {
		r1 = rf(usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
